[
  {"pdf_name":"Computer organization and architecture : designing for performance","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(1).pdf"},
  {"pdf_name":"Introduction to Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(2).pdf"},
  {"pdf_name":"Fundamentals of Database Systems","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(3).pdf"},
  {"pdf_name":"Computer Graphics, C Version","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(4).pdf"},
  {"pdf_name":"CSE 143 Lecture 5: More Stacks and Queues; Complexity (Big-Oh)","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(5).pdf"},
  {"pdf_name":"Advanced .NET Debugging","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(6).pdf"},
  {"pdf_name":"Advanced windows debugging","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(7).pdf"},
  {"pdf_name":"Artificial intelligence","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(8).pdf"},
  {"pdf_name":"C: The Complete Reference","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(9).pdf"},
  {"pdf_name":"C: An Advanced Introduction","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(10).pdf"},
  {"pdf_name":"CLR via C#","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(11).pdf"},
  {"pdf_name":"Compilers. Principles, Techniques, & Tools","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(12).pdf"},
  {"pdf_name":"Software Engineering: A Practitioner's Approach","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(13).pdf"},
  {"pdf_name":"Data Communications And Networking","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(14).pdf"},
  {"pdf_name":"Domain-Driven Design Quickly","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(15).pdf"},
  {"pdf_name":"Systems programming","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(16).pdf"},
  {"pdf_name":"Essential Scrum","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(17).pdf"},
  {"pdf_name":"Expert C Programming: Deep C Secrets","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(18).pdf"},
  {"pdf_name":"Expert Python Programming","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(19).pdf"},
  {"pdf_name":"Head First Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(20).pdf"},
  {"pdf_name":"Java: The Complete Reference","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(21).pdf"},
  {"pdf_name":"Jumping into C++","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(22).pdf"},
  {"pdf_name":"A Tour of C++","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(23).pdf"},
  {"pdf_name":"Mobile Communications","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(24).pdf"},
  {"pdf_name":"Distributed Process Management","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(25).pdf"},
  {"pdf_name":"The Data Compression Book","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(26).pdf"},
  {"pdf_name":"HTML: Pocket Reference","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(27).pdf"},
  {"pdf_name":"IPv6 Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(28).pdf"},
  {"pdf_name":"JavaScript Application Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(29).pdf"},
  {"pdf_name":"Learning Oracle PL/SQL","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(30).pdf"},
  {"pdf_name":"The C++ Standard Library","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(31).pdf"},
  {"pdf_name":"Learning Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(32).pdf"},
  {"pdf_name":"Learning the UNIX Operating System","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(33).pdf"},
  {"pdf_name":"Learning the vi and Vim Editors","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(34).pdf"},
  {"pdf_name":"Learning the vi Editor","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(35).pdf"},
  {"pdf_name":"Alphabetical Directory of Linux Commands","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(36).pdf"},
  {"pdf_name":"Linux Network Administrator's Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(37).pdf"},
  {"pdf_name":"Linux Networking Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(38).pdf"},
  {"pdf_name":"Hacker's Delight","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(39).pdf"},
  {"pdf_name":"Mastering Regular Expressions","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(40).pdf"},
  {"pdf_name":"MySQL Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(41).pdf"},
  {"pdf_name":"MySQL: Pocket Reference","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(42).pdf"},
  {"pdf_name":"Practical C++ Programming","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(43).pdf"},
  {"pdf_name":"Python & XML","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(44).pdf"},
  {"pdf_name":"Modern C++ Design: Generic Programming and Design Patterns Applied","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(45).pdf"},
  {"pdf_name":"Python for Unix and Linux System Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(46).pdf"},
  {"pdf_name":"Real World Instrumentation with Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(47).pdf"},
  {"pdf_name":"Ruby in a Nutshell","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(48).pdf"},
  {"pdf_name":"Running Linux","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(49).pdf"},
  {"pdf_name":"sed & awk","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(50).pdf"},
  {"pdf_name":"Server Load Balancing","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(51).pdf"},
  {"pdf_name":"SSH, The Secure Shell: The Definitive Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(52).pdf"},
  {"pdf_name":"Accelerated C++: Practical Programming by Example","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(53).pdf"},
  {"pdf_name":"The Productive Programmer","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(54).pdf"},
  {"pdf_name":"A Byte of Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(55).pdf"},
  {"pdf_name":"Understanding the Linux Kernel","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(56).pdf"},
  {"pdf_name":"C: How To Program","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(57).pdf"},
  {"pdf_name":"Operating System Concepts","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(58).pdf"},
  {"pdf_name":"Patterns for Parallel Programming","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(59).pdf"},
  {"pdf_name":"Pragmatic Guide to Git","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(60).pdf"},
  {"pdf_name":"Data Science from Scratch","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(61).pdf"},
  {"pdf_name":"Principles of Distributed Database Systems","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(62).pdf"},
  {"pdf_name":"Pro .NET Performance: Optimize Your C# Applications","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(63).pdf"},
  {"pdf_name":"Python: Create-Modify-Reuse","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(64).pdf"},
  {"pdf_name":"Python Power! The Comprehensive Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(65).pdf"},
  {"pdf_name":"Rx Design Guidelines","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(66).pdf"},
  {"pdf_name":"Software Engineering","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(67).pdf"},
  {"pdf_name":"Succeeding with Agile","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(68).pdf"},
  {"pdf_name":"Systems Analysis and Design in a Changing World","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(69).pdf"},
  {"pdf_name":"Human–computer interaction","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(70).pdf"},
  {"pdf_name":"The Essential Guide to User Interface Design","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(71).pdf"},
  {"pdf_name":"About Face 3: The Essentials of Interaction Design","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(72).pdf"},
  {"pdf_name":"Designing with the Mind in Mind","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(73).pdf"},
  {"pdf_name":"The Design of Everyday Things","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(74).pdf"},
  {"pdf_name":"The Quick Python Book","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(75).pdf"},
  {"pdf_name":"The Art of Unit Testing","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(76).pdf"},
  {"pdf_name":"The Python Standard Library by Example","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(77).pdf"},
  {"pdf_name":"C++ Concurrency in Action","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(78).pdf"},
  {"pdf_name":"UML","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(79).pdf"},
  {"pdf_name":"When Should I Use Parallel.ForEach? When Should I Use PLINQ?","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(80).pdf"},
  {"pdf_name":"Windows Internals (Part 1)","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(81).rar"},
  {"pdf_name":"Windows Internals (Part 2)","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(82).pdf"},
  {"pdf_name":"WinRT Revealed","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(83).pdf"},
  {"pdf_name":"XML Schema Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(84).pdf"},
  {"pdf_name":"Creating your MySQL Database: Practical Design Tips and Techniques","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(85).pdf"},
  {"pdf_name":"Graph Databases","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(86).pdf"},
  {"pdf_name":"Learning Azure DocumentDB","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(87).pdf"},
  {"pdf_name":"Learning Neo4j","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(88).pdf"},
  {"pdf_name":"Learning PostgreSQL","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(89).pdf"},
  {"pdf_name":"Mastering RethinkDB","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(90).pdf"},
  {"pdf_name":"Microsoft SQL Azure: Enterprise Application Development","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(91).pdf"},
  {"pdf_name":"Microsoft SQL Server 2012 Integration Services: An Expert Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(92).pdf"},
  {"pdf_name":"MongoDB Basics","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(93).pdf"},
  {"pdf_name":"MySQL for Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(94).pdf"},
  {"pdf_name":"Oracle Database 11gR2 Performance Tuning Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(95).pdf"},
  {"pdf_name":"PostgreSQL 9 Administration Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(96).pdf"},
  {"pdf_name":"PostgreSQL 9 High Availability Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(97).pdf"},
  {"pdf_name":"PostgreSQL 9 Development Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(98).pdf"},
  {"pdf_name":"PostgreSQL Server Programming","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(99).pdf"},
  {"pdf_name":"SQL Server 2014 Development Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(100).pdf"},
  {"pdf_name":"SQL Server 2016 Reporting Services Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(101).pdf"},
  {"pdf_name":"The Definitive Guide to MongoDB","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(102).pdf"},
  {"pdf_name":"Advanced Bash-Scripting Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(103).pdf"},
  {"pdf_name":"Automate it!: Recipes to upskill your business","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(104).pdf"},
  {"pdf_name":"Clean Code: A Handbook of Agile Software Craftsmanship","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(105).pdf"},
  {"pdf_name":"Beginning the Linux Command Line","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(106).pdf"},
  {"pdf_name":"Building Microservices","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(107).pdf"},
  {"pdf_name":"CentOS 6 Linux Server Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(108).pdf"},
  {"pdf_name":"Continuous Delivery and DevOps: A Quickstart Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(109).pdf"},
  {"pdf_name":"CoreOS Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(110).pdf"},
  {"pdf_name":"Designing and Implementing Linux Firewalls and QoS using netfilter, iproute2, NAT, and L7-filter","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(111).pdf"},
  {"pdf_name":"Developing Microservices with Node.js","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(112).pdf"},
  {"pdf_name":"DevOps Automation Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(113).pdf"},
  {"pdf_name":"DevOps Bootcamp: A fast-paced guide to implement DevOps with ease","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(114).pdf"},
  {"pdf_name":"DevOps for Networking","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(115).pdf"},
  {"pdf_name":"DevOps for Web Development","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(116).pdf"},
  {"pdf_name":"DevOps on the Microsoft Stack","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(117).pdf"},
  {"pdf_name":"DevOps with Windows Server 2016","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(118).pdf"},
  {"pdf_name":"DEVOPS, DBAS, AND DBAAS","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(119).pdf"},
  {"pdf_name":"Effective DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(120).pdf"},
  {"pdf_name":"Getting Started with tmux","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(121).pdf"},
  {"pdf_name":"GNU/Linux Advanced Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(122).pdf"},
  {"pdf_name":"Implementing DevOps on AWS","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(123).pdf"},
  {"pdf_name":"Implementing Modern DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(124).pdf"},
  {"pdf_name":"Infrastructure as Code (IAC) Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(125).pdf"},
  {"pdf_name":"Jenkins Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(126).pdf"},
  {"pdf_name":"Learn Windows PowerShell 3 in a Month of Lunches","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(127).pdf"},
  {"pdf_name":"Learning Continuous Integration with Jenkins","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(128).pdf"},
  {"pdf_name":"Learning DevOps: Continuously Deliver Better Software","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(129).pdf"},
  {"pdf_name":"Learning Linux Shell Scripting","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(130).pdf"},
  {"pdf_name":"Learning Shell Scripting with Zsh","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(131).pdf"},
  {"pdf_name":"Linux Bible","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(132).pdf"},
  {"pdf_name":"Linux E-mail: Set up, maintain, and secure a small office e-mail server","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(133).pdf"},
  {"pdf_name":"Linux Email: Set up and Run a Small Office Email Server","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(134).pdf"},
  {"pdf_name":"Linux For Dummies","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(135).pdf"},
  {"pdf_name":"Linux in a Nutshell","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(136).pdf"},
  {"pdf_name":"Linux Mint Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(137).pdf"},
  {"pdf_name":"Exceptional C++: 47 Engineering Puzzles, Programming Problems, and Solutions","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(138).pdf"},
  {"pdf_name":"Linux: Pocket Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(139).pdf"},
  {"pdf_name":"Linux Shell Scripting Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(140).pdf"},
  {"pdf_name":"Linux Shell Scripting Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(141).pdf"},
  {"pdf_name":"Linux Thin Client Networks Design and Deployment","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(142).pdf"},
  {"pdf_name":"Linux Utilities Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(143).pdf"},
  {"pdf_name":"Mastering Linux Shell Scripting","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(144).pdf"},
  {"pdf_name":"Mastering Linux","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(145).pdf"},
  {"pdf_name":"Mastering Wireshark","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(146).pdf"},
  {"pdf_name":"Mesos in Action","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(147).pdf"},
  {"pdf_name":"Microservices: Building Scalable Software","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(148).pdf"},
  {"pdf_name":"Microservices: Flexible Software Architecture","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(149).pdf"},
  {"pdf_name":"Microservices Deployment Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(150).pdf"},
  {"pdf_name":"Microservices from Day One","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(151).pdf"},
  {"pdf_name":"Modern Linux Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(152).pdf"},
  {"pdf_name":"Nmap Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(153).pdf"},
  {"pdf_name":"PowerShell in Depth","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(154).pdf"},
  {"pdf_name":"PowerShell in Practice","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(155).pdf"},
  {"pdf_name":"PowerShell Succinctly","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(156).pdf"},
  {"pdf_name":"Practical DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(157).pdf"},
  {"pdf_name":"Pro Bash Programming: Scripting the GNU/Linux Shell","url":"https://github.com/manjunath5496/Computer-Science).pdf"},
  {"pdf_name":"Building Microservices","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(107).pdf"},
  {"pdf_name":"CentOS 6 Linux Server Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(108).pdf"},
  {"pdf_name":"Continuous Delivery and DevOps: A Quickstart Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(109).pdf"},
  {"pdf_name":"CoreOS Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(110).pdf"},
  {"pdf_name":"Designing and Implementing Linux Firewalls and QoS using netfilter, iproute2, NAT, and L7-filter","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(111).pdf"},
  {"pdf_name":"Developing Microservices with Node.js","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(112).pdf"},
  {"pdf_name":"DevOps Automation Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(113).pdf"},
  {"pdf_name":"DevOps Bootcamp: A fast-paced guide to implement DevOps with ease","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(114).pdf"},
  {"pdf_name":"DevOps for Networking","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(115).pdf"},
  {"pdf_name":"DevOps for Web Development","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(116).pdf"},
  {"pdf_name":"DevOps on the Microsoft Stack","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(117).pdf"},
  {"pdf_name":"DevOps with Windows Server 2016","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(118).pdf"},
  {"pdf_name":"DEVOPS, DBAS, AND DBAAS","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(119).pdf"},
  {"pdf_name":"Effective DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(120).pdf"},
  {"pdf_name":"Getting Started with tmux","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(121).pdf"},
  {"pdf_name":"GNU/Linux Advanced Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(122).pdf"},
  {"pdf_name":"Implementing DevOps on AWS","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(123).pdf"},
  {"pdf_name":"Implementing Modern DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(124).pdf"},
  {"pdf_name":"Infrastructure as Code (IAC) Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(125).pdf"},
  {"pdf_name":"Jenkins Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(126).pdf"},
  {"pdf_name":"Learn Windows PowerShell 3 in a Month of Lunches","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(127).pdf"},
  {"pdf_name":"Learning Continuous Integration with Jenkins","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(128).pdf"},
  {"pdf_name":"Learning DevOps: Continuously Deliver Better Software","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(129).pdf"},
  {"pdf_name":"Learning Linux Shell Scripting","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(130).pdf"},
  {"pdf_name":"Learning Shell Scripting with Zsh","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(131).pdf"},
  {"pdf_name":"Linux Bible","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(132).pdf"},
  {"pdf_name":"Linux E-mail: Set up, maintain, and secure a small office e-mail server","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(133).pdf"},
  {"pdf_name":"Linux Email: Set up and Run a Small Office Email Server","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(134).pdf"},
  {"pdf_name":"Linux For Dummies","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(135).pdf"},
  {"pdf_name":"Linux in a Nutshell","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(136).pdf"},
  {"pdf_name":"Linux Mint Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(137).pdf"},
  {"pdf_name":"Exceptional C++: 47 Engineering Puzzles, Programming Problems, and Solutions","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(138).pdf"},
  {"pdf_name":"Linux: Pocket Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(139).pdf"},
  {"pdf_name":"Linux Shell Scripting Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(140).pdf"},
  {"pdf_name":"Linux Shell Scripting Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(141).pdf"},
  {"pdf_name":"Linux Thin Client Networks Design and Deployment","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(142).pdf"},
  {"pdf_name":"Linux Utilities Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(143).pdf"},
  {"pdf_name":"Mastering Linux Shell Scripting","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(144).pdf"},
  {"pdf_name":"Mastering Linux","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(145).pdf"},
  {"pdf_name":"Mastering Wireshark","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(146).pdf"},
  {"pdf_name":"Mesos in Action","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(147).pdf"},
  {"pdf_name":"Microservices: Building Scalable Software","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(148).pdf"},
  {"pdf_name":"Microservices: Flexible Software Architecture","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(149).pdf"},
  {"pdf_name":"Microservices Deployment Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(150).pdf"},
  {"pdf_name":"Microservices from Day One","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(151).pdf"},
  {"pdf_name":"Modern Linux Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(152).pdf"},
  {"pdf_name":"Nmap Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(153).pdf"},
  {"pdf_name":"PowerShell in Depth","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(154).pdf"},
  {"pdf_name":"PowerShell in Practice","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(155).pdf"},
  {"pdf_name":"PowerShell Succinctly","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(156).pdf"},
  {"pdf_name":"Practical DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(157).pdf"},
  {"pdf_name":"Pro Bash Programming: Scripting the GNU/Linux Shell","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(158).pdf"},
  {"pdf_name":"Pro Continuous Delivery With Jenkins 2.0","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(159).pdf"},
  {"pdf_name":"REST API Design Rulebook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(160).pdf"},
  {"pdf_name":"SELinux System Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(161).pdf"},
  {"pdf_name":"Shell Scripting Recipes: A Problem-Solution Approach","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(162).pdf"},
  {"pdf_name":"The DevOps 2.0 Toolkit: Automating the Continuous Deployment Pipeline With Containerized Microservices","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(163).pdf"},
  {"pdf_name":"The DevOps 2.1 Toolkit: Docker Swarm","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(164).pdf"},
  {"pdf_name":"The DevOps Adoption Playbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(165).pdf"},
  {"pdf_name":"The Linux Command Line: A Complete Introduction","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(166).pdf"},
  {"pdf_name":"The Linux Programming Interface","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(167).pdf"},
  {"pdf_name":"tmux Master","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(168).pdf"},
  {"pdf_name":"X Power Tools","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(169).pdf"},
  {"pdf_name":"Vagrant Virtual Development Environment Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(170).pdf"},
  {"pdf_name":"Windows PowerShell 3.0 First Steps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(171).pdf"},
  {"pdf_name":"Windows PowerShell Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(172).pdf"},
  {"pdf_name":"Windows PowerShell in Action","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(173).pdf"},
  {"pdf_name":"Windows PowerShell: Pocket Reference","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(174).pdf"},
  {"pdf_name":"Wireshark Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(175).pdf"},
  {"pdf_name":"Wireshark Network Security","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(176).pdf"},
  {"pdf_name":"Working with Linux – Quick Hacks for the Command Line","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(177).pdf"},
  {"pdf_name":"Your UNIX/Linux: The Ultimate Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(178).pdf"},
  {"pdf_name":"Pro SQL Server Internals","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(179).pdf"},
  {"pdf_name":"Data Structures and Algorithms in Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(180).pdf"},
  {"pdf_name":"Data Structures and Algorithms with JavaScript","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(181).pdf"},
  {"pdf_name":"Programming Pearls","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(182).pdf"},
  {"pdf_name":"Data Structures And Algorithms Made Easy","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(183).pdf"},
  {"pdf_name":"Data Structures and Algorithms with Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(184).pdf"},
  {"pdf_name":"Disk-Based Algorithms for Big Data","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(185).pdf"},
  {"pdf_name":"Dynamic Programming: A Computational Tool","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(186).pdf"},
  {"pdf_name":"Grokking Algorithms: An illustrated guide for programmers and other curious people","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(187).rar"},
  {"pdf_name":"Introduction to Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(188).pdf"},
  {"pdf_name":"Learning F# Functional Data Structures and Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(189).pdf"},
  {"pdf_name":"Learning JavaScript Data Structures and Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(190).rar"},
  {"pdf_name":"Mathematics and Physics for Programmers","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(191).pdf"},
  {"pdf_name":"Python Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(192).pdf"},
  {"pdf_name":"Sets, Logic and Maths for Computing","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(193).pdf"},
  {"pdf_name":"The Algorithm Design Manual","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(194).pdf"},
  {"pdf_name":"Deep Learning with Python: A Hands-on Introduction","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(195).pdf"},
  {"pdf_name":"Deep Learning with Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(196).pdf"},
  {"pdf_name":"Discovering Modern C++: An Intensive Course for Scientists, Engineers, and Programmers","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(197).rar"},
  {"pdf_name":"Effective STL: 50 Specific Ways to Improve Your Use of the Standard Template Library","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(198).pdf"},
  {"pdf_name":"C++: The Complete Reference","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(199).pdf"},
  {"pdf_name":"Hadoop with Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(200).pdf"},
  {"pdf_name":"HMI Framework 2.0 User Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(201).pdf"},
  {"pdf_name":"LEARN PYTHON THE HARD WAY: A Very Simple Introduction to the Terrifyingly Beautiful World of Computers and Code","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(202).pdf"},
  {"pdf_name":"Numerical Recipes in C: The Art of Scientific Computing","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(203).pdf"},
  {"pdf_name":"The Art of Computer Programming, Volume 1: Fundamental Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(204).pdf"},
  {"pdf_name":"The Art of Computer Programming, Volume 3: Sorting and Searching","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(205).pdf"},
  {"pdf_name":"The Art of Computer Programming: Seminumerical Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(206).pdf"},
  {"pdf_name":"Effective Java","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(207).pdf"},
  {"pdf_name":"Functional Programming for Java Developers","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(208).pdf"},
  {"pdf_name":"Java ).pdf"},
  {"pdf_name":"Building Microservices","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(107).pdf"},
  {"pdf_name":"CentOS 6 Linux Server Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(108).pdf"},
  {"pdf_name":"Continuous Delivery and DevOps: A Quickstart Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(109).pdf"},
  {"pdf_name":"CoreOS Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(110).pdf"},
  {"pdf_name":"Designing and Implementing Linux Firewalls and QoS using netfilter, iproute2, NAT, and L7-filter","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(111).pdf"},
  {"pdf_name":"Developing Microservices with Node.js","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(112).pdf"},
  {"pdf_name":"DevOps Automation Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(113).pdf"},
  {"pdf_name":"DevOps Bootcamp: A fast-paced guide to implement DevOps with ease","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(114).pdf"},
  {"pdf_name":"DevOps for Networking","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(115).pdf"},
  {"pdf_name":"DevOps for Web Development","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(116).pdf"},
  {"pdf_name":"DevOps on the Microsoft Stack","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(117).pdf"},
  {"pdf_name":"DevOps with Windows Server 2016","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(118).pdf"},
  {"pdf_name":"DEVOPS, DBAS, AND DBAAS","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(119).pdf"},
  {"pdf_name":"Effective DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(120).pdf"},
  {"pdf_name":"Getting Started with tmux","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(121).pdf"},
  {"pdf_name":"GNU/Linux Advanced Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(122).pdf"},
  {"pdf_name":"Implementing DevOps on AWS","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(123).pdf"},
  {"pdf_name":"Implementing Modern DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(124).pdf"},
  {"pdf_name":"Infrastructure as Code (IAC) Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(125).pdf"},
  {"pdf_name":"Jenkins Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(126).pdf"},
  {"pdf_name":"Learn Windows PowerShell 3 in a Month of Lunches","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(127).pdf"},
  {"pdf_name":"Learning Continuous Integration with Jenkins","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(128).pdf"},
  {"pdf_name":"Learning DevOps: Continuously Deliver Better Software","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(129).pdf"},
  {"pdf_name":"Learning Linux Shell Scripting","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(130).pdf"},
  {"pdf_name":"Learning Shell Scripting with Zsh","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(131).pdf"},
  {"pdf_name":"Linux Bible","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(132).pdf"},
  {"pdf_name":"Linux E-mail: Set up, maintain, and secure a small office e-mail server","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(133).pdf"},
  {"pdf_name":"Linux Email: Set up and Run a Small Office Email Server","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(134).pdf"},
  {"pdf_name":"Linux For Dummies","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(135).pdf"},
  {"pdf_name":"Linux in a Nutshell","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(136).pdf"},
  {"pdf_name":"Linux Mint Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(137).pdf"},
  {"pdf_name":"Exceptional C++: 47 Engineering Puzzles, Programming Problems, and Solutions","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(138).pdf"},
  {"pdf_name":"Linux: Pocket Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(139).pdf"},
  {"pdf_name":"Linux Shell Scripting Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(140).pdf"},
  {"pdf_name":"Linux Shell Scripting Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(141).pdf"},
  {"pdf_name":"Linux Thin Client Networks Design and Deployment","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(142).pdf"},
  {"pdf_name":"Linux Utilities Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(143).pdf"},
  {"pdf_name":"Mastering Linux Shell Scripting","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(144).pdf"},
  {"pdf_name":"Mastering Linux","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(145).pdf"},
  {"pdf_name":"Mastering Wireshark","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(146).pdf"},
  {"pdf_name":"Mesos in Action","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(147).pdf"},
  {"pdf_name":"Microservices: Building Scalable Software","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(148).pdf"},
  {"pdf_name":"Microservices: Flexible Software Architecture","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(149).pdf"},
  {"pdf_name":"Microservices Deployment Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(150).pdf"},
  {"pdf_name":"Microservices from Day One","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(151).pdf"},
  {"pdf_name":"Modern Linux Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(152).pdf"},
  {"pdf_name":"Nmap Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(153).pdf"},
  {"pdf_name":"PowerShell in Depth","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(154).pdf"},
  {"pdf_name":"PowerShell in Practice","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(155).pdf"},
  {"pdf_name":"PowerShell Succinctly","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(156).pdf"},
  {"pdf_name":"Practical DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(157).pdf"},
  {"pdf_name":"Pro Bash Programming: Scripting the GNU/Linux Shell","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(158).pdf"},
  {"pdf_name":"Pro Continuous Delivery With Jenkins 2.0","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(159).pdf"},
  {"pdf_name":"REST API Design Rulebook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(160).pdf"},
  {"pdf_name":"SELinux System Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(161).pdf"},
  {"pdf_name":"Shell Scripting Recipes: A Problem-Solution Approach","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(162).pdf"},
  {"pdf_name":"The DevOps 2.0 Toolkit: Automating the Continuous Deployment Pipeline With Containerized Microservices","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(163).pdf"},
  {"pdf_name":"The DevOps 2.1 Toolkit: Docker Swarm","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(164).pdf"},
  {"pdf_name":"The DevOps Adoption Playbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(165).pdf"},
  {"pdf_name":"The Linux Command Line: A Complete Introduction","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(166).pdf"},
  {"pdf_name":"The Linux Programming Interface","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(167).pdf"},
  {"pdf_name":"tmux Master","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(168).pdf"},
  {"pdf_name":"X Power Tools","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(169).pdf"},
  {"pdf_name":"Vagrant Virtual Development Environment Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(170).pdf"},
  {"pdf_name":"Windows PowerShell 3.0 First Steps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(171).pdf"},
  {"pdf_name":"Windows PowerShell Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(172).pdf"},
  {"pdf_name":"Windows PowerShell in Action","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(173).pdf"},
  {"pdf_name":"Windows PowerShell: Pocket Reference","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(174).pdf"},
  {"pdf_name":"Wireshark Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(175).pdf"},
  {"pdf_name":"Wireshark Network Security","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(176).pdf"},
  {"pdf_name":"Working with Linux – Quick Hacks for the Command Line","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(177).pdf"},
  {"pdf_name":"Your UNIX/Linux: The Ultimate Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(178).pdf"},
  {"pdf_name":"Pro SQL Server Internals","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(179).pdf"},
  {"pdf_name":"Data Structures and Algorithms in Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(180).pdf"},
  {"pdf_name":"Data Structures and Algorithms with JavaScript","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(181).pdf"},
  {"pdf_name":"Programming Pearls","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(182).pdf"},
  {"pdf_name":"Data Structures And Algorithms Made Easy","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(183).pdf"},
  {"pdf_name":"Data Structures and Algorithms with Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(184).pdf"},
  {"pdf_name":"Disk-Based Algorithms for Big Data","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(185).pdf"},
  {"pdf_name":"Dynamic Programming: A Computational Tool","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(186).pdf"},
  {"pdf_name":"Grokking Algorithms: An illustrated guide for programmers and other curious people","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(187).rar"},
  {"pdf_name":"Introduction to Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(188).pdf"},
  {"pdf_name":"Learning F# Functional Data Structures and Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(189).pdf"},
  {"pdf_name":"Learning JavaScript Data Structures and Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(190).rar"},
  {"pdf_name":"Mathematics and Physics for Programmers","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(191).pdf"},
  {"pdf_name":"Python Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(192).pdf"},
  {"pdf_name":"Sets, Logic and Maths for Computing","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(193).pdf"},
  {"pdf_name":"The Algorithm Design Manual","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(194).pdf"},
  {"pdf_name":"Deep Learning with Python: A Hands-on Introduction","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(195).pdf"},
  {"pdf_name":"Deep Learning with Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(196).pdf"},
  {"pdf_name":"Discovering Modern C++: An Intensive Course for Scientists, Engineers, and Programmers","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(197).rar"},
  {"pdf_name":"Effective STL: 50 Specific Ways to Improve Your Use of the Standard Template Library","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(198).pdf"},
  {"pdf_name":"C++: The Complete Reference","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(199).pdf"},
  {"pdf_name":"Hadoop with Python","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(200).pdf"},
  {"pdf_name":"HMI Framework 2.0 User Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(201).pdf"},
  {"pdf_name":"LEARN PYTHON THE HARD WAY: A Very Simple Introduction to the Terrifyingly Beautiful World of Computers and Code","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(202).pdf"},
  {"pdf_name":"Numerical Recipes in C: The Art of Scientific Computing","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(203).pdf"},
  {"pdf_name":"The Art of Computer Programming, Volume 1: Fundamental Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(204).pdf"},
  {"pdf_name":"The Art of Computer Programming, Volume 3: Sorting and Searching","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(205).pdf"},
  {"pdf_name":"The Art of Computer Programming: Seminumerical Algorithms","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(206).pdf"},
  {"pdf_name":"Effective Java","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(207).pdf"},
  {"pdf_name":"Functional Programming for Java Developers","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(208).pdf"},
  {"pdf_name":"Java ).pdf"},
  {"pdf_name":"Building Microservices","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(107).pdf"},
  {"pdf_name":"CentOS 6 Linux Server Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(108).pdf"},
  {"pdf_name":"Continuous Delivery and DevOps: A Quickstart Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(109).pdf"},
  {"pdf_name":"CoreOS Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(110).pdf"},
  {"pdf_name":"Designing and Implementing Linux Firewalls and QoS using netfilter, iproute2, NAT, and L7-filter","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(111).pdf"},
  {"pdf_name":"Developing Microservices with Node.js","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(112).pdf"},
  {"pdf_name":"DevOps Automation Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(113).pdf"},
  {"pdf_name":"DevOps Bootcamp: A fast-paced guide to implement DevOps with ease","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(114).pdf"},
  {"pdf_name":"DevOps for Networking","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(115).pdf"},
  {"pdf_name":"DevOps for Web Development","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(116).pdf"},
  {"pdf_name":"DevOps on the Microsoft Stack","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(117).pdf"},
  {"pdf_name":"DevOps with Windows Server 2016","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(118).pdf"},
  {"pdf_name":"DEVOPS, DBAS, AND DBAAS","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(119).pdf"},
  {"pdf_name":"Effective DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(120).pdf"},
  {"pdf_name":"Getting Started with tmux","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(121).pdf"},
  {"pdf_name":"GNU/Linux Advanced Administration","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(122).pdf"},
  {"pdf_name":"Implementing DevOps on AWS","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(123).pdf"},
  {"pdf_name":"Implementing Modern DevOps","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(124).pdf"},
  {"pdf_name":"Infrastructure as Code (IAC) Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(125).pdf"},
  {"pdf_name":"Jenkins Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(126).pdf"},
  {"pdf_name":"Learn Windows PowerShell 3 in a Month of Lunches","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(127).pdf"},
  {"pdf_name":"Learning Continuous Integration with Jenkins","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(128).pdf"},
  {"pdf_name":"Learning DevOps: Continuously Deliver Better Software","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(129).pdf"},
  {"pdf_name":"Learning Linux Shell Scripting","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(130).pdf"},
  {"pdf_name":"Learning Shell Scripting with Zsh","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(131).pdf"},
  {"pdf_name":"Linux Bible","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(132).pdf"},
  {"pdf_name":"Linux E-mail: Set up, maintain, and secure a small office e-mail server","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(133).pdf"},
  {"pdf_name":"Linux Email: Set up and Run a Small Office Email Server","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(134).pdf"},
  {"pdf_name":"Linux For Dummies","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(135).pdf"},
  {"pdf_name":"Linux in a Nutshell","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(136).pdf"},
  {"pdf_name":"Linux Mint Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(137).pdf"},
  {"pdf_name":"Exceptional C++: 47 Engineering Puzzles, Programming Problems, and Solutions","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(138).pdf"},
  {"pdf_name":"Linux: Pocket Guide","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(139).pdf"},
  {"pdf_name":"Linux Shell Scripting Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(140).pdf"},
  {"pdf_name":"Linux Shell Scripting Essentials","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(141).pdf"},
  {"pdf_name":"Linux Thin Client Networks Design and Deployment","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(142).pdf"},
  {"pdf_name":"Linux Utilities Cookbook","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(143).pdf"},
  {"pdf_name":"Mastering Linux Shell Scripting","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(144).pdf"},
  {"pdf_name":"Mastering Linux","url":"https://github.com/manjunath5496/Computer-Science-Reference-Books/blob/master/comp(145).pdf"}]